name: Simple CI

on:
  push:
    branches:
      - main

env:
  VAR_TEST: "1234"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ENV_TEST

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a on-line script
        run: echo "Hello, world! VAR_TEST is $VAR_TEST"

      - name: Run test secret
        run: echo "secret test is ${{ secrets.TEST_SECRET }}"

      - name: Run test secret env
        run: echo "secret test env is ${{ secrets.ENV_TEST_SECRET }}"

      - name: Run test var
        run: echo "secret test is ${{vars.REP_VAR }}"

      - name: Run test var env
        run: echo "secret test env is ${{ vars.VAR_ENV }}"
