name: Simple CI

on:
  push:
    branches:
      - main

env:
  VAR_TEST: "1234"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a on-line script
        run: echo "Hello, world! VAR_TEST : ${{ $VAR_TEST }}"
